common/models/Vlan.php
<?php

namespace common\models;

use Yii;
use yii\data\ActiveDataProvider;
use common\components\Setup;

/**
 * This is the model class for table "tb_vlan".
 *
 * @property int $id
 * @property int $unidade_fk
 * @property int $id_vlan
 * @property string $vlan
 * @property string $descricao_vlan
 *
 */
class Vlan extends \yii\db\ActiveRecord
{
    public $pesquisa;
    
    public static function tableName()
    {
        return 'tb_vlan';
    }
    
    public function rules()
    {
        return [
            [['unidade_fk', 'id_vlan', 'vlan', 'descricao_vlan'], 'required'],
            [['unidade_fk', 'id_vlan'], 'default', 'value' => null],
            [['unidade_fk', 'id_vlan'], 'integer'],
            [['vlan'], 'string', 'max' => 20],
            [['descricao_vlan'], 'string', 'max' => 80],
            [['unidade_fk', 'id_vlan'], 'unique', 'targetAttribute' => ['unidade_fk', 'id_vlan']],
            [['unidade_fk'], 'exist', 'skipOnError' => true, 'targetClass' => Unidade::className(), 'targetAttribute' => ['unidade_fk' => 'id']],
        ];
    }
    
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'unidade_fk' => 'Unidade',
            'id_vlan' => 'ID VLAN',
            'vlan' => 'Nome VLAN',
            'descricao_vlan' => 'Descricao VLAN',
        ];
    }
    
    public function getUnidadeFk()
    {
        return $this->hasOne(Unidade::className(), ['id' => 'unidade_fk']);
    }
    
    public function search($params) {
        $query = Vlan::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => [
                'defaultOrder' => [
                    'id_vlan' => SORT_ASC,
                ]
            ],
        ]);

        if (isset($params['Vlan']['pesquisa'])) {
            $query->orFilterWhere(['like', 'UPPER(fc_remove_acento(vlan))', strtoupper(Setup::retirarAcento($params['Vlan']['pesquisa']))])
                    ->orFilterWhere(['like', 'UPPER(fc_remove_acento(descricao))', strtoupper(Setup::retirarAcento($params['Vlan']['pesquisa']))]);
        }
        
        $usuariounidade = UsuarioUnidade::find()->select('unidade_fk')->Where(['usuario_fk' => Yii::$app->user->identity->id])->andWhere(['>', 'unidade_fk', '1']);
        
        if (Yii::$app->user->identity->unidade_temp_fk != '1') {
            $query->andFilterWhere(['unidade_fk' => [1, Yii::$app->user->identity->unidade_temp_fk]]);
        } else {
            $query->andFilterWhere(['IN', 'unidade_fk', $usuariounidade]);
        }

        $dataProvider->setTotalCount($query->count());
        
        return $dataProvider;
    }
}

backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\Usuario;
use common\models\Sistema;
use common\models\Configuracao;
use common\models\UsuarioPerfil;
use common\models\UsuarioUnidade;
use common\components\SendMail;
use common\components\Setup;

use common\models\Computador;
use common\models\Monitor;
use common\models\Equipamento;
use common\models\HdCadastro;
use common\models\HdUsuarioUnidade;
use common\models\ApiJavaComputador;

/**
 * Site controller
 */
class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'qr', 'apijavacomp', 'new-password', 'reset-password'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'set-session-unidade', 'profile'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['get'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        if (Yii::$app->session->isActive) {
            $rodape = Configuracao::findOne(1);
            Yii::$app->session->set("rodape_interno", $rodape->variavel2);
            
            $url = Sistema::findOne(1);
            Yii::$app->session->set("url", $url->url);
            
            $usuarioperfil = UsuarioPerfil::find()->where(['usuario_fk' => Yii::$app->user->identity->id])->one();
            Yii::$app->session->set("usuarioperfil", $usuarioperfil->perfil_fk);
            
        }

        $usuario_trocar_senha =  Usuario::find()->where(['id' => Yii::$app->user->identity->id])->one();

        if ($usuario_trocar_senha->trocar_senha == 1) {
            return $this->redirect(['site/new-password?token=' . $usuario_trocar_senha->token ]);
        } else {
            $usuariounidade = UsuarioUnidade::find()->select('unidade_fk')->Where(['usuario_fk' => Yii::$app->user->identity->id])->andWhere(['>', 'unidade_fk', '1']);
            
            $usuariounidadehd = HdUsuarioUnidade::find()->select('unidade_fk')->Where(['usuario_fk' => Yii::$app->user->identity->id])->andWhere(['>', 'unidade_fk', '1']);

            $computador_total = Computador::find()->distinct()
                ->Where(['=', 'status', '1'])
                ->andWhere(['IN', 'unidade_fk', $usuariounidade])
                ->all();
            $monitor_total = Monitor::find()->distinct()
                ->Where(['=', 'status', '1'])
                ->andWhere(['IN', 'unidade_fk', $usuariounidade])
                ->all();
            $equipamento_total = Equipamento::find()->distinct()
                ->Where(['=', 'status', '1'])
                ->andWhere(['IN', 'unidade_fk', $usuariounidade])
                ->all();
            $hd_total = HdCadastro::find()->distinct()
                ->Where(['=', 'status', '4'])
                ->andWhere(['IN', 'unidade_fk', $usuariounidadehd])
                ->all();
            $usuario_total = Usuario::find()->distinct()
                ->Where(['=', 'status', '1'])
                ->andWhere(['IN', 'unidade_fk', $usuariounidade])
                ->all();
            
            
            return $this->render('index', [
                'computador_total' => $computador_total,
                'monitor_total' => $monitor_total,
                'equipamento_total' => $equipamento_total,
                'hd_total' => $hd_total,
                'usuario_total' => $usuario_total,
            ]);
        }
    }

    public function actionQr($codigo) {
        $this->layout = "main_qr";
        
        switch($codigo[0]) { 
            case "C" :
                $model = Computador::findOne(['codigo_computador' => $codigo]);
                return $this->render('qrcomputador', [
                    'model' => $model,
                ]);
                break; 
            case "M" :
                $model = Monitor::findOne(['codigo_monitor' => $codigo]);
                return $this->render('qrmonitor', [
                    'model' => $model,
                ]);
                break; 
            case "E" :
                $model = Equipamento::findOne(['codigo_equipamento' => $codigo]);
                return $this->render('qrequipamento', [
                    'model' => $model,
                ]);
                break;
        }
        return $this->render('qr');
    }

    public function actionApijavacomp() {
        
        // Recebe o JSON enviado por uma requisição POST
        $json = file_get_contents('php://input');

        // Converte o JSON em um array associativo
        $data = json_decode($json, true);

        // Verifica se o JSON foi decodificado com sucesso
        if ($data === null) {
            // Erro na decodificação do JSON
            http_response_code(400); // Define o código de resposta HTTP para 400 Bad Request
            echo "Erro na decodificação do JSON.";
            exit;
        }

        $model_codigo_computador = Computador::findOne(['codigo_computador' => $data['codComp']]);

        $model_busca_computador = ApiJavaComputador::findOne(['codigo_computador_fk' => $model_codigo_computador->id]);

        if ($model_busca_computador != null) {
            $model = $this->findModel($model_busca_computador->id);
            $model->data = date('d/m/Y H:i:s');

            $model->versao_so = $data['osVersion'];
            $model->nome_so = $data['osName'];
            $model->arquitetura_so = $data['osArch'];
            $model->memoria_ram = $data['totalMemory'];
            $model->memoria_live = $data['freeMemory'];
            $model->processador = $data['processor'];
            $model->macaddres_1 = $data['macAddress1'];
            $model->macaddres_2 = $data['macAddress2'];
            $model->macaddres_3 = $data['macAddress3'];
    
            $model->save();
        } else {
            $model = new ApiJavaComputador();
            $model->codigo_computador_fk = $model_codigo_computador->id;
            $model->unidade_fk = $model_codigo_computador->unidade_fk;
            $model->data = date('d/m/Y H:i:s');

            $model->versao_so = $data['osVersion'];
            $model->nome_so = $data['osName'];
            $model->arquitetura_so = $data['osArch'];
            $model->memoria_ram = $data['totalMemory'];
            $model->memoria_live = $data['freeMemory'];
            $model->processador = $data['processor'];
            $model->macaddres_1 = $data['macAddress1'];
            $model->macaddres_2 = $data['macAddress2'];
            $model->macaddres_3 = $data['macAddress3'];

            $model->save();
        }
        
    }

    protected function findModel($id) {
        if (($model = ApiJavaComputador::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('A página solicitada não existe.');
        }
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin() {
        $this->layout = "main_login";
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';
            return $this->render('login', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout() {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    public function actionSetSessionUnidade() {
        $model = Usuario::findOne(Yii::$app->user->identity->id);
        $request = Yii::$app->request->post();
        if ($model) {
            $model->unidade_temp_fk = $request['unidade_temp_fk'];
            $model->save();
        }
        Yii::$app->user->identity->unidade_temp_fk = $request['unidade_temp_fk'];
    }
    
    public function actionResetPassword() {
        $this->layout = "main_login";
        $model = new Usuario();

        if (Yii::$app->request->isAjax) {
            if ($model->load(Yii::$app->request->post())) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
        } else {
            if ($model->load(Yii::$app->request->post())) {
                $model = Usuario::find()->where(['email' => $model->email])->all();
                foreach ($model as $key => $value) {
                    $value->token = Yii::$app->security->generateRandomString();
                    if ($value->save()) {
                        Yii::$app->mailer->compose([
                                    'html' => 'novo_cadastro_insignare-html',
                                    'text' => 'novo_cadastro_insignare-text'
                                        ], [
                                    'model' => $value
                                ])->setFrom([
                                    'insignare@acpr.org.br' => 'SGT'
                                ])->setTo($value->email)

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class=" card-box">
    <div class="panel-heading"> 
        <h3 class="text-center"> <?php echo Html::encode($this->title) ?> </h3>
    </div> 

    <p>Por favor, preencha os seguintes campos para entrar:</p>

    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?php echo $form->field($model, 'username')->textInput(['autofocus' => true]); ?>

                <?php echo $form->field($model, 'password')->passwordInput(); ?>

                <div class="form-group">
                    <?php echo Html::submitButton('Entrar', ['class' => 'btn btn-primary', 'name' => 'login-button']); ?>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>

backend/views/site/perfil.php
<?php

use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;
use common\models\Unidade;

$this->title = 'Usuario';
?>

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-border panel-primary">
            <div class="panel-heading">
                <h3 class="m-t-0 header-title"><?php echo $title; ?></h3>
            </div>
            <div class="panel-body">

                <?php $form = ActiveForm::begin(); ?>

                <div class="row">
                    <div class="col-sm-6">
                        <?php echo $form->field($model, 'nome')->textInput(['class' => 'form-control', 'maxlength' => true, 'autofocus' => true]) ?>
                    </div>
                    <div class="col-sm-6">
                        <?php echo $form->field($model, 'email')->textInput(['class' => 'form-control', 'maxlength' => true]) ?>
                    </div>            
                </div>
                <div class="row">
                    <div class="col-sm-5">
                        <?php echo $form->field($model, 'senha')->passwordInput(['class' => 'form-control', 'maxlength' => true, 'onkeyup' => 'javascript:verifica_forca(this.value)']) ?>
                    </div>
                    <div class="col-sm-1">
                        <br>
                        <span id="mostra"></span>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label"><?php echo $model->getAttributeLabel('unidade'); ?></label>
                            <input type="text" class="form-control" disabled="" value="<?php echo $model->unidadeFk->unidade; ?>">
                        </div>                                        
                    </div>
                </div>
                <div class="form-group text-right m-b-0">
                    <?php echo Html::submitButton($model->isNewRecord ? Yii::t('app', '<i class="ion-checkmark-round"></i> Salvar') : Yii::t('app', '<i class="ion-checkmark-round"></i> Salvar'), ['class' => 'btn btn-primary waves-effect waves-light']) ?>
                </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>
</div>

<?php
    $this->registerJs("
        function verifica_forca(senha){
            forca = 0;
            mostra = document.getElementById('mostra');
            if((senha.length > 7) && (senha.length <= 12)){
                forca += 10;
            }else if((senha.length>12)){
                forca += 25;
            }
            if(senha.match(/[a-z]+/)){
                forca += 10;
            }
            if(senha.match(/[A-Z]+/)){
                forca += 20;
            }
            if(senha.match(/\d+/)){
                forca += 20;
            }
            if(senha.match(/\W+/)){
                forca += 25;
            }
            return mostra_res();
            return libera_aplicar();
        }
        function mostra_res(){
            if(forca <=30){
                mostra.innerHTML = '<span style=\"color:#FF0000;\"> Fraca </span>';
            }else if((forca > 30) && (forca < 60)){
                mostra.innerHTML = '<span style=\"color:#FFBE00;\"> Boa </span>'; 
            }else if((forca >= 60) && (forca < 85)){
                mostra.innerHTML = '<span style=\"color:#0000FF;\"> Forte </span>';
            }else {
                mostra.innerHTML = '<span style=\"color:#00CD00;\"> Excelente </span>';
            }
        }
       ", View::POS_END, 'functions-usuario-password'
    );
?>

backend/views/site/qrcomputador.php
<?php

/* @var $this yii\web\View */

$this->title = 'QR';
?>
<div class="site-index">
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('codigo_computador'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->codigo_computador; ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('unidade_fk'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->unidadeFk->unidade; ?>">
            </div>                                        
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('setor_fk'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php
                    echo ($model->setor_fk != NULL ? $model->setorFk->setor : "Setor não informado" )
                ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('tipo_fk'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->tipoFk->tipo; ?>">
            </div>                                        
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label">Marca</label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->modeloFk->marcaFk->marca; ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('modelo_fk'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->modeloFk->modelo; ?>">
            </div>                                        
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('numero_serie'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->numero_serie; ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('netbios'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->netbios; ?>">
            </div>                                        
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('mac_c'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->mac_c; ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('mac_w'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->mac_w; ?>">
            </div>                                        
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('data_compra'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->data_compra; ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('garantia'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->garantia; ?>">
            </div>                                        
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('numero_lacre'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->numero_lacre; ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('placa_mae'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->placa_mae; ?>">
            </div>                                        
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('processador_fk'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php
                    echo ($model->processador_fk != NULL ? $model->processadorFk->processador : "Sem Processaor" )
                ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('numero_processador'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->numero_processador; ?>">
            </div>                                        
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('ram'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->ram.' '.$model->ramMedidaFk->simbolo; ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('ram_clok_fk'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php
                    echo ($model->ram_clok_fk != NULL ? $model->ramClokFk->clok.' MHz' : "Sem Clok" )
                ?>">
            </div>                                        
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('hd'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->hd.' '.$model->hdMedidaFk->simbolo; ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('tipo_hd_fk'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php
                    echo ($model->placa_video_fk != NULL ? $model->tipoHdFk->tipo : "Sem Tipo de HD" )
                ?>">
            </div>                                        
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('numero_patrimonio'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->numero_patrimonio; ?>">
            </div>                                        
        </div>
    </div>
</div>

backend/views/site/qrequipamento.php
<?php

/* @var $this yii\web\View */

$this->title = 'QR';
?>
<div class="site-index">
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('codigo_equipamento'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->codigo_equipamento; ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('unidade_fk'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->unidadeFk->unidade; ?>">
            </div>                                        
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('setor_fk'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php
                    echo ($model->setor_fk != NULL ? $model->setorFk->setor : "Setor não informado" )
                ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('tipo_fk'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->tipoFk->tipo; ?>">
            </div>                                        
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label">Marca</label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->modeloFk->marcaFk->marca; ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('modelo_fk'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->modeloFk->modelo; ?>">
            </div>                                        
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('numero_serie'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->numero_serie; ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('netbios'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->netbios; ?>">
            </div>                                        
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('mac'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->mac; ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('numero_patrimonio'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->numero_patrimonio; ?>">
            </div>                                        
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('data_compra'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->data_compra; ?>">
            </div>                                        
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label"><?php echo $model->getAttributeLabel('garantia'); ?></label>
                <input type="text" class="form-control" disabled="" value="<?php echo $model->garantia; ?>">
            </div>                                        
        </div>
    </div>
</div>